runtime: python312

env_variables:
  # Database configuration
  MONGODB_URL: "your-mongodb-connection-string"
  DATABASE_NAME: "your-database-name"
  
  # API Keys
  OPENAI_API_KEY: "your-openai-key"
  GEMINI_API_KEY: "your-gemini-key"
  GROQ_API_KEY: "your-groq-key"
  
  # Application settings
  MAX_FILE_SIZE: "10485760"  # 10MB
  UPLOAD_DIR: "/tmp/uploads"

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 2
  memory_gb: 2

handlers:
- url: /.*
  script: auto